version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
  open-pull-requests-limit: 10
  assignees:
  - rdela
  labels:
  - dependencies
  ignore:
  - dependency-name: cypress
    versions:
    - 6.5.0
  commit-message:
    prefix: chore
    include: scope
