[build]
  command = "SAPPER_TIMESTAMP=$(date +%s%3N) npm run export"
  publish = "__sapper__/export"

[build.environment]
  NODE_ENV = "development"
  NODE_VERSION = "--lts"
  NPM_VERSION = "6.14.11"
  RUBY_VERSION = "default"
